import {Router} from 'express';
import * as c from '../controllers/customer.controller.js';
import {authenticate} from '../middleware/auth.js';
import {validate} from '../middleware/validate.js';
import {addressSchema,cartSchema,checkoutSchema,searchHistorySchema,supportTicketSchema} from '../validators/schemas.js';

export const customerRouter=Router();
customerRouter.use(authenticate);
customerRouter.get('/users/me',c.profile.get);
customerRouter.patch('/users/me',c.profile.update);
customerRouter.get('/addresses',c.addresses.list);
customerRouter.post('/addresses',validate(addressSchema),c.addresses.create);
customerRouter.patch('/addresses/:id',c.addresses.update);
customerRouter.delete('/addresses/:id',c.addresses.remove);
customerRouter.patch('/addresses/:id/default',c.addresses.makeDefault);
customerRouter.get('/favorites',c.favorites.list);
customerRouter.post('/favorites/:productId',c.favorites.add);
customerRouter.delete('/favorites/:productId',c.favorites.remove);
customerRouter.get('/cart',c.cart.get);
customerRouter.put('/cart/items',validate(cartSchema),c.cart.set);
customerRouter.delete('/cart',c.cart.clear);
customerRouter.get('/search-history',c.searchHistory.list);
customerRouter.post('/search-history',validate(searchHistorySchema),c.searchHistory.add);
customerRouter.delete('/search-history/:query',c.searchHistory.remove);
customerRouter.delete('/search-history',c.searchHistory.clear);
customerRouter.get('/coupons',c.coupons);
customerRouter.post('/coupons/validate',c.couponValidate);
customerRouter.post('/checkout',validate(checkoutSchema),c.checkout);
customerRouter.get('/orders',c.orders.list);
customerRouter.get('/orders/:id',c.orders.get);
customerRouter.get('/support',c.support.list);
customerRouter.post('/support',validate(supportTicketSchema),c.support.create);
