import net from 'node:net';
import tls from 'node:tls';
import {env} from '../config/env.js';
import {AppError} from '../utils/response.js';

const command=(socket,value)=>socket.write(`${value}\r\n`);
const response=(socket,codes)=>new Promise((resolve,reject)=>{let buffer='';const clean=()=>{socket.off('data',data);socket.off('error',fail)};const fail=error=>{clean();reject(error)};const data=chunk=>{buffer+=chunk.toString('utf8');const last=buffer.trimEnd().split(/\r?\n/).at(-1)||'';if(!/^\d{3}\s/.test(last))return;const code=Number(last.slice(0,3));clean();codes.includes(code)?resolve(buffer):reject(new Error(buffer))};socket.on('data',data);socket.on('error',fail)});
const connect=()=>new Promise((resolve,reject)=>{const options={host:env.smtpHost,port:env.smtpPort,servername:env.smtpHost,rejectUnauthorized:env.smtpRejectUnauthorized};const socket=env.smtpSecure?tls.connect(options,()=>resolve(socket)):net.connect(options,()=>resolve(socket));socket.once('error',reject)});
const upgrade=socket=>new Promise((resolve,reject)=>{const secure=tls.connect({socket,servername:env.smtpHost,rejectUnauthorized:env.smtpRejectUnauthorized},()=>resolve(secure));secure.once('error',reject)});
const safe=value=>String(value).replace(/^\./gm,'..').replace(/[\r\n]+/g,' ');
async function smtp({to,subject,body}){let socket=await connect();try{await response(socket,[220]);command(socket,`EHLO ${env.smtpHost}`);await response(socket,[250]);if(!env.smtpSecure){command(socket,'STARTTLS');await response(socket,[220]);socket=await upgrade(socket);command(socket,`EHLO ${env.smtpHost}`);await response(socket,[250])}command(socket,'AUTH LOGIN');await response(socket,[334]);command(socket,Buffer.from(env.smtpUser).toString('base64'));await response(socket,[334]);command(socket,Buffer.from(env.smtpPass.replace(/\s/g,'')).toString('base64'));await response(socket,[235]);command(socket,`MAIL FROM:<${env.smtpFrom}>`);await response(socket,[250]);command(socket,`RCPT TO:<${to}>`);await response(socket,[250,251]);command(socket,'DATA');await response(socket,[354]);const message=[`From: Grocify <${env.smtpFrom}>`,`To: ${safe(to)}`,`Subject: ${safe(subject)}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=utf-8','',body].join('\r\n').replace(/^\./gm,'..');command(socket,`${message}\r\n.`);await response(socket,[250]);command(socket,'QUIT')}finally{socket.end()}}
export async function sendOtpEmail(to,otp){if(env.otpProvider!=='smtp'){if(env.nodeEnv==='production')throw new AppError('SMTP email delivery is not configured',503);console.log(`Grocify OTP for ${to}: ${otp}`);return}try{await smtp({to,subject:'Your Grocify verification code',body:[`Your Grocify verification code is ${otp}.`,'',`This code expires in ${env.otpMinutes} minutes.`,'Never share this code with anyone.','If you did not request this, you can safely ignore this email.'].join('\r\n')})}catch(error){console.error('SMTP delivery failed:',error.message);if(/535|534|5\.7\.[89]|auth/i.test(error.message))throw new AppError('SMTP login was rejected. Check the email App Password.',503);if(/ENOTFOUND|ECONNREFUSED|ETIMEDOUT/i.test(error.message))throw new AppError('Email service is temporarily unreachable.',503);throw new AppError('Could not send the verification email. Please try again.',503)}}
