import {z} from 'zod';
const envelope=(body=z.any(),params=z.any(),query=z.any())=>z.object({body,params,query});
const password=z.string().min(8,'Password must contain at least 8 characters').max(72);
export const customerLoginSchema=envelope(z.object({email:z.email().toLowerCase(),password}));
export const otpRequestSchema=envelope(z.union([z.object({email:z.email().toLowerCase(),mode:z.literal('signup'),name:z.string().trim().min(2).max(80),mobile:z.string().regex(/^\d{10}$/),password}),z.object({email:z.email().toLowerCase(),mode:z.literal('signup')})]));
export const otpVerifySchema=envelope(z.object({email:z.email().toLowerCase(),mode:z.literal('signup'),otp:z.string().regex(/^\d{6}$/)}));
export const adminLoginSchema=envelope(z.object({email:z.email(),password:z.string().min(6)}));
export const addressSchema=envelope(z.object({name:z.string().min(2),mobile:z.string().min(10),house:z.string().min(1),street:z.string().optional().default(''),landmark:z.string().optional().default(''),area:z.string().min(2),city:z.string().min(2),district:z.string().optional().default(''),state:z.string().min(2),pin:z.string().regex(/^\d{6}$/),type:z.enum(['Home','Work','Other']).default('Home'),isDefault:z.boolean().optional().default(false)}));
export const cartSchema=envelope(z.object({productId:z.string(),quantity:z.number().int().min(0).max(99)}));
export const searchHistorySchema=envelope(z.object({query:z.string().trim().min(2).max(100)}));
export const checkoutSchema=envelope(z.object({addressId:z.string(),couponCode:z.string().optional(),deliveryInstruction:z.string().max(300).optional(),paymentMethod:z.literal('COD').default('COD')}));
