import {z} from 'zod';
import {serviceableLocalities} from '../data/serviceableLocalities.js';
const envelope=(body=z.any(),params=z.any(),query=z.any())=>z.object({body,params,query});
const password=z.string().min(8,'Password must contain at least 8 characters').max(72);
export const customerLoginSchema=envelope(z.object({email:z.email().toLowerCase(),password}));
export const otpRequestSchema=envelope(z.union([z.object({email:z.email().toLowerCase(),mode:z.literal('signup'),name:z.string().trim().min(2).max(80),mobile:z.string().regex(/^\d{10}$/),password}),z.object({email:z.email().toLowerCase(),mode:z.literal('signup')})]));
export const otpVerifySchema=envelope(z.object({email:z.email().toLowerCase(),mode:z.literal('signup'),otp:z.string().regex(/^\d{6}$/)}));
export const adminLoginSchema=envelope(z.object({email:z.email(),password:z.string().min(6)}));
export const addressSchema=envelope(z.object({name:z.string().min(2),mobile:z.string().regex(/^\d{10}$/),house:z.string().optional().default(''),street:z.string().optional().default(''),landmark:z.string().optional().default(''),area:z.enum(serviceableLocalities),city:z.literal('Hathua'),district:z.string().optional().default(''),state:z.string().optional().default(''),pin:z.union([z.literal(''),z.string().regex(/^\d{6}$/)]).optional().default(''),type:z.string().trim().min(2).max(30).default('Home'),isDefault:z.boolean().optional().default(false)}));
export const cartSchema=envelope(z.object({productId:z.string(),quantity:z.number().int().min(0).max(99)}));
export const searchHistorySchema=envelope(z.object({query:z.string().trim().min(2).max(100)}));
export const checkoutSchema=envelope(z.object({addressId:z.string(),couponCode:z.string().optional(),deliveryInstruction:z.string().max(300).optional(),paymentMethod:z.literal('COD').default('COD')}));
export const supportTicketSchema=envelope(z.object({issueType:z.enum(['Order issue','Payment issue','Delivery issue','Product issue','General query','Suggestions']),orderId:z.string().nullable().optional(),subject:z.string().trim().min(4).max(120),description:z.string().trim().min(10).max(2000)}));
